config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :channels, only: [:index] do
    member do
      get 'add', controller: 'channels', action: 'add', as: 'add'
      get 'remove', controller: 'channels', action: 'remove', as: 'remove'
      get 'entries', controller: 'entries', action: 'index', as: 'entries'
    end
  end
  resources :import, only: [:index, :create]
  resources :entries, only: [:index, :show] do
    collection do
      # get 'channel/:channel_id', controller: 'entries', action: 'index', as: 'channel'
      get 'get_body', action: 'get_body', as: 'get_body'
      get 'flagged', action: 'flagged', as: 'flagged'
      get 'starred', action: 'starred', as: 'starred'
      post "action/:id/:method", action: "action", as: "action"
      post "batch_actions", action: "batch_actions", as: "batch_actions"
    end
  end

  root 'entries#index'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  searchkick

  has_many :entries
  has_many :users
  has_many :users, through: :users

  scope :locked, ->{ where(locked: false) }
  scope :other, ->(ids) { where.not(id: ids).locked }

  # разбить на 2 метода
  def feed_changed?(feed)
    sha = Digest::SHA2.hexdigest(feed.entries.map{ |f| f.title }.join(' '))
    if last_feed_sha == sha
      false
    else
      update_attributes(last_feed_sha: sha)
      true
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @user_channels = current_user.channels
    @other_channels = Channel.other current_user.channel_ids
  end

  def add
    @channel = Channel.find(params[:id])
    current_user.channels << @channel
    redirect_to channels_path
  end

  def remove
    @channel = Channel.find(params[:id])
    current_user.channels.delete(@channel)
    redirect_to channels_path
  end
end

app/views/channels/index.html.haml
.index_channels
  .head
    %h3 My channels
  - if @user_channels.present?
    - @user_channels.each do |channel|
      .index_channel
        .actions
          / %span.info
          = link_to '', remove_channel_path(channel), class: :remove
        .body
          %span.title
            = link_to channel.title, entries_channel_path(channel)
          %span.summary
            = channel.text
  - else
    .empty_channels You have no any channels yet

.index_channels
  .head
    %h3 Other channels
  - @other_channels.each do |channel|
    .index_channel
      .actions
        / %span.info
        / # = link_to '', remove_channel_path(channel), class: :remove
        = link_to '', add_channel_path(channel), class: :add
      .body
        %span.title
          = link_to channel.title, entries_channel_path(channel)
        %span.summary
          = channel.text