config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :channels, only: [:index] do
    member do
      get 'add', controller: 'channels', action: 'add', as: 'add'
      get 'remove', controller: 'channels', action: 'remove', as: 'remove'
      get 'entries', controller: 'entries', action: 'index', as: 'entries'
    end
  end
  resources :import, only: [:index, :create]
  resources :entries, only: [:index, :show] do
    collection do
      # get 'channel/:channel_id', controller: 'entries', action: 'index', as: 'channel'
      get 'get_body', action: 'get_body', as: 'get_body'
      get 'flagged', action: 'flagged', as: 'flagged'
      get 'starred', action: 'starred', as: 'starred'
      post "action/:id/:method", action: "action", as: "action"
      post "batch_actions", action: "batch_actions", as: "batch_actions"
    end
  end

  root 'entries#index'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  include GetFeeds
  include GetEntryBody
  searchkick callbacks: false

  belongs_to :channel

  scope :ordering,  -> { order(published_at: :desc) }
  scope :entries, ->(q, ids, page, per) { search q, where: {channel_id: ids}, order: {published_at: :desc}, page: page, per_page: per }

  def self.batch
    %w(read unread flag unflag star unstar)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :entry
  respond_to :html, :js

  def index
    channel_ids = params.fetch(:id, false) ? params[:id] : UserChannel.user_channel_ids(current_user.id)
    query = params.fetch(:query, false) && !params[:query].blank? ? params[:query] : '*'
    @entries = Entry.entries(query, channel_ids, params[:page], 29)
  end

  def flagged
    @entries = current_user.flagged_entry.page(params[:page])
    render :index
  end

  def starred
    @entries = current_user.starred_entry.page(params[:page])
    render :index
  end

  def show
    current_user.read(@entry.id)
    @entry
  end

  def action
    @method = params[:method]
    @entry = Entry.find(params[:id])
    entry_action @entry, @method
  end

  def batch_actions
    @method = params['method']
    @entries = Entry.where(id: params[:entry][:ids])
    @entries.each { |entry| entry_action entry, @method }
  end

  def get_body
    @entry.get_body
  end

  private
  def entry
    @entry = Entry.find(params[:id]) if params[:id]
  end

  def entry_action(entry, method)
    current_user.send("#{method}", entry.id) unless current_user.send("#{prepare_method(method)}ed?", entry.id)
  end

  def prepare_method(method)
    if method == 'star' || method == 'unstar'
      "#{method}r"
    elsif method == 'flag' || method == 'unflag'
      "#{method}g"
    elsif method == 'read' || method == 'unread'
      method
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def subscribed_channel?(channel)
    current_user.user_channel_ids.include?(channel.to_i)
  end

  def subscribe_channel(channel)
    return if subscribed_channel?(channel)
    content_tag :span, class: :add do
      link_to 'Add this channel', add_channel_path(id: channel)
    end
  end
end

app/views/entries/_entry_list.html.haml
.index_entries{ role: :index_entries }
  = render partial: 'entry_list_item', collection: @entries, as: :entry

app/views/entries/_entry_list_item.html.haml
%div{ class: "index_entry #{current_user.readed?(entry.id) ? 'read' : ''}", id: "entry_#{entry.id}"}
  .actions
    %span.square{ role: 'check' }
    = check_box_tag 'entry[ids][]', entry.id, false

    = link_to action_entries_path(entry, current_user.starred?(entry.id) ? :unstar : :star), remote: true, method: :post do
      %span.star{ role: 'star', class: current_user.starred?(entry.id) ? 'check' : '' }

    = link_to action_entries_path(entry, current_user.flagged?(entry.id) ? :unflag : :flag), remote: true, method: :post do
      %span.flag{ role: 'flag', class: current_user.flagged?(entry.id) ? 'check' : '' }
  .body
    %span{ class: "group_color_#{entry.channel.color}", role: "tooltip", title: entry.channel.title, data: { placement: "bottom" } }
    %span.title
      = link_to entry.name, entry_path(entry)
      \–
    %span.summary
      = strip_tags entry.summary
  %span.date
    = entry.published_at.to_date.to_formatted_s(:short) if entry.published_at

app/views/entries/_search.html.haml
= form_tag entries_path, class: "search", method: :get do
  = search_field_tag :query, params[:query], placeholder: 'Search'
  = submit_tag "Search"
  - if params[:query].present?
    = link_to "Clear", entries_path

app/views/entries/action.js.erb
$('#entry_<%= @entry.id %>').replaceWith('<%=j render "entry_list_item", entry: @entry %>')

app/views/entries/batch_actions.js.erb
<%- @entries.each do |entry| %>
  $('#entry_<%= entry.id %>').replaceWith('<%=j render "entry_list_item", entry: entry %>')
  $('@check_all').toggleClass('check')
<% end -%>

app/views/entries/get_body.js.erb
$('@show_entry').replaceWith("<%=j render template: 'entries/show' %>")

app/views/entries/index.html.haml
.search_container
  = render 'search'
.content
  = form_tag batch_actions_entries_path, remote: true do
    .actions_menu
      %span.square{ role: 'check_all' }
      - %w{read flag star}.each do |action|
        = button_tag action.capitalize, remote: true, method: :post, type: :submit, name: :method, value: "#{action}"
        = button_tag "Un#{action}", remote: true, method: :post, type: :submit, name: :method, value: "un#{action}"
      = subscribe_channel(params[:id]) if params.fetch(:id, false)

    = render 'entry_list'
    - if @entries.present?
      = paginate @entries

app/views/entries/index.js.erb
$('@index_entries').html("<%=j render partial: 'entry_list_item', collection: @entries, as: :entry %>")

app/views/entries/show.html.haml
.show_entry{role: 'show_entry'}
  %h3
    = @entry.name
  %small.channel
    = link_to @entry.channel.title, @entry.url, target: '_blank'
    = @entry.published_at.to_formatted_s(:long)
    = link_to 'View all entries', entries_channel_path(@entry.channel), class: :view
    = subscribe_channel(@entry.channel.id)
  - if @entry.body.blank?
    .summary
      = preserve do
        = raw @entry.summary.gsub("\t", "  ").gsub("<br><br>", "<br>") unless @entry.summary.nil?
      .empty_entry
        = link_to 'Get body', get_body_entries_path(id: @entry.id), class: 'button', remote: true, data: {disable_with: 'Geting... body'}
  - else
    .body
      = preserve do
        = raw @entry.body unless @entry.summary.nil?