config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :channels, only: [:index] do
    member do
      get 'add', controller: 'channels', action: 'add', as: 'add'
      get 'remove', controller: 'channels', action: 'remove', as: 'remove'
      get 'entries', controller: 'entries', action: 'index', as: 'entries'
    end
  end
  resources :import, only: [:index, :create]
  resources :entries, only: [:index, :show] do
    collection do
      # get 'channel/:channel_id', controller: 'entries', action: 'index', as: 'channel'
      get 'get_body', action: 'get_body', as: 'get_body'
      get 'flagged', action: 'flagged', as: 'flagged'
      get 'starred', action: 'starred', as: 'starred'
      post "action/:id/:method", action: "action", as: "action"
      post "batch_actions", action: "batch_actions", as: "batch_actions"
    end
  end

  root 'entries#index'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/layouts/_sidebar.html.haml
- if user_signed_in?
  %ul
    %li
      = link_to entries_path do
        Inbox
        %span.count
          = current_user.unread_count
      readed_count
    %li
      = link_to flagged_entries_path do
        Flagged
        %span.count
          = current_user.flagged_count
    %li
      = link_to starred_entries_path do
        Starred
        %span.count
          = current_user.starred_count
    %li
      = link_to 'Channels', channels_path
    %li
      = link_to 'Import from OPML', import_index_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ereader
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{ id: rand(10..20) }
    .page_container
      .sidebar
        = render 'layouts/sidebar'
      .main_content{ role: :main_content }
        .notice
          = notice
        .alert
          = alert
        .container
          = yield
    .loading.hidden{ role: :loading }
      Loading...

    %link{ rel: "stylesheet", href: "http://yandex.st/highlightjs/8.0/styles/default.min.css" }
    %script{ src: "http://yandex.st/highlightjs/8.0/highlight.min.js" }
    %link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato" }